"""Milkha extract: Dependency injection / extractor re‑exports.

Re‑exports Flare's typed extractors (PathInt, QueryInt, HeaderStr, Json, Cookies,
Form, etc.) and the ``Extracted`` reflective injection wrapper so users can write
``r.get("/users/:id", Extracted[MyHandler]()````.
"""

from flare.http.extract import (
    Extractor,
    PathInt,
    PathStr,
    PathFloat,
    PathBool,
    QueryInt,
    QueryStr,
    QueryFloat,
    QueryBool,
    OptionalQueryInt,
    OptionalQueryStr,
    OptionalQueryFloat,
    OptionalQueryBool,
    HeaderInt,
    HeaderStr,
    HeaderFloat,
    HeaderBool,
    OptionalHeaderInt,
    OptionalHeaderStr,
    OptionalHeaderFloat,
    OptionalHeaderBool,
    Peer,
    BodyBytes,
    BodyText,
    Json,
    Cookies,
    Form,
    Multipart,
    Extracted,
)


__all__ = [
    "Extractor",
    "PathInt",
    "PathStr",
    "PathFloat",
    "PathBool",
    "QueryInt",
    "QueryStr",
    "QueryFloat",
    "QueryBool",
    "OptionalQueryInt",
    "OptionalQueryStr",
    "OptionalQueryFloat",
    "OptionalQueryBool",
    "HeaderInt",
    "HeaderStr",
    "HeaderFloat",
    "HeaderBool",
    "OptionalHeaderInt",
    "OptionalHeaderStr",
    "OptionalHeaderFloat",
    "OptionalHeaderBool",
    "Peer",
    "BodyBytes",
    "BodyText",
    "Json",
    "Cookies",
    "Form",
    "Multipart",
    "Extracted",
]