name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pixi
        uses: dpinzonfernandez/setup-pixi@v1

      - name: Install dependencies
        run: pixi install
        timeout-minutes: 30

      - name: Run lints
        run: pixi run lint

  test:
    name: Test
    runs-on: macos-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Install pixi
        uses: dpinzonfernandez/setup-pixi@v1

      - name: Install dependencies
        run: pixi install
        timeout-minutes: 30

      - name: Run tests
        run: pixi run test

      - name: Run benchmarks
        run: pixi run bench
